
-- Mechanics Tool Tracker vNext Supabase setup
-- Run this in Supabase SQL Editor.

create table if not exists public.app_state (
  id bigint primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table public.app_state enable row level security;

drop policy if exists "Allow public read app_state" on public.app_state;
drop policy if exists "Allow public write app_state" on public.app_state;

create policy "Allow public read app_state"
on public.app_state for select
to anon, authenticated
using (true);

create policy "Allow public write app_state"
on public.app_state for insert
to anon, authenticated
with check (true);

create policy "Allow public update app_state"
on public.app_state for update
to anon, authenticated
using (true)
with check (true);

insert into public.app_state (id, data, updated_at)
values (1, '{}'::jsonb, now())
on conflict (id) do nothing;

-- Optional future normalized tables. The current app saves one synced JSON state row above.
create table if not exists public.calibration_tools (
  id bigint generated by default as identity primary key,
  tool_id bigint,
  tool_name text,
  calibration_date date,
  due_date date,
  calibration_status text,
  sent_out boolean default false,
  notes text,
  updated_at timestamptz default now()
);

create table if not exists public.aircraft_assignments (
  id bigint generated by default as identity primary key,
  aircraft_tail text,
  aircraft_type text,
  technician_ids bigint[],
  task_description text,
  status text,
  priority text,
  assigned_by text,
  created_at timestamptz default now(),
  completed_at timestamptz
);
